default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: workout_playlist_generator_development

test:
  <<: *default
  database: workout_playlist_generator_test

production:
  <<: *default
  database: workout_playlist_generator_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
