:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  :schedule:
    process_users_workouts_worker:
      cron: "0 * * * *" # Every hour at the top of the hour
      class: "ProcessUsersWorkoutsWorker"
      queue: high
    clean_up_spotify_playlists_worker:
      cron: "0 * * * *" # Every hour at the top of the hour
      class: "CleanUpSpotifyPlaylistsWorker"
      queue: low
