:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  :schedule:
    process_users_workouts_job:
      every: '1h'
      class: 'ProcessUsersWorkoutsWorker'
