:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  :schedule:
    process_all_workouts_job:
      cron: "*/5 * * * *" # Every 5 minutes
      class: "ProcessAllWorkoutsJob"
      queue: high

    clean_up_playlists_job:
      cron: "*/5 * * * *" # Every 5 minutes
      class: "CleanUpPlaylistsJob"
      queue: low
