:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  :schedule:
    process_users_workouts_worker:
      cron: "*/5 * * * *" # Every 5 minutes
      class: "ProcessAllWorkoutsJob"
      queue: high

    clean_up_spotify_playlists_worker:
      cron: "*/5 * * * *" # Every 5 minutes
      class: "CleanUpSpotifyPlaylistsJob"
      queue: low
